package com.sinyuk.jianyimaterial.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SCHOOL".
 */
public class School implements java.io.Serializable {

    /** Not-null value. */
    private String id;
    /** Not-null value. */
    private String name;
    private String coord;
    private String x;
    private String y;

    // KEEP FIELDS - put your custom fields here

    // KEEP FIELDS END

    public School() {
    }

    public School(String id) {
        this.id = id;
    }

    public School(String id, String name, String coord, String x, String y) {
        this.id = id;
        this.name = name;
        this.coord = coord;
        this.x = x;
        this.y = y;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getCoord() {
        return coord;
    }

    public void setCoord(String coord) {
        this.coord = coord;
    }

    public String getX() {
        return x;
    }

    public void setX(String x) {
        this.x = x;
    }

    public String getY() {
        return y;
    }

    public void setY(String y) {
        this.y = y;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
