package com.sinyuk.jianyimaterial.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sinyuk.jianyimaterial.entity.User;
import com.sinyuk.jianyimaterial.entity.YihuoDetails;
import com.sinyuk.jianyimaterial.entity.School;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig yihuoDetailsDaoConfig;
    private final DaoConfig schoolDaoConfig;

    private final UserDao userDao;
    private final YihuoDetailsDao yihuoDetailsDao;
    private final SchoolDao schoolDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        yihuoDetailsDaoConfig = daoConfigMap.get(YihuoDetailsDao.class).clone();
        yihuoDetailsDaoConfig.initIdentityScope(type);

        schoolDaoConfig = daoConfigMap.get(SchoolDao.class).clone();
        schoolDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        yihuoDetailsDao = new YihuoDetailsDao(yihuoDetailsDaoConfig, this);
        schoolDao = new SchoolDao(schoolDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(YihuoDetails.class, yihuoDetailsDao);
        registerDao(School.class, schoolDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        yihuoDetailsDaoConfig.getIdentityScope().clear();
        schoolDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public YihuoDetailsDao getYihuoDetailsDao() {
        return yihuoDetailsDao;
    }

    public SchoolDao getSchoolDao() {
        return schoolDao;
    }

}
